name: quran_reading_v2
description: تطبيق تصحيح التلاوة باستخدام الذكاء الاصطناعي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.3.8

  # HTTP & API
  http: ^1.1.2

  # Audio Recording & Playback
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/backend/config/daily_plan.json

  # Fonts (يمكن إضافة خط Cairo العربي لاحقاً)
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: fonts/Cairo-Regular.ttf
  #       - asset: fonts/Cairo-Bold.ttf
  #         weight: 700